language: c
env:
  secure: BknrdaosTPToC5+bM1ASEr0X8DFnebigsJfdKctJRN34p87P2bYY3mA+xkQzkF5vxtxiXa/zlsbLHEfXs9Jn/1JuPYCtlZLhIn3o6YSBYP9WTce0OlfzjBAb6Ab/ddj421DSYTv8TiUcHKHyH9acjlstjxtUuY/n2NteDp3CBj2S+8sJVeJjj2UlUKomi+TA5G0LUdEcuIGfT8nCp2z8D7DO1LEONg08KtfHPvBwJeyndzSDrBj/OhfYRcGNEdG7E61ew3v8iQ7AtqWZvc3pTfatC3NMVfvwuNEEHQIZlYrlMsqs/akMgmjS8n3mRJJq97Ptug0m3PsV6ZZiGCZJRrzOi0UFVrKVGeLeemmlPbwFm/1G7Z516ENeNpb7TbOjGSJnXIdiqSBDju+EQsuRierE3du/L2jikEP2FCMxpUf5CkT7hklXK7cxqXs+pAscGLr/jsMDm6geLtfOBHJ6n/mJqLUQtxr9F2snzP4glF8kWhvfF1xFj3Z8M/3FOiuHhxXvLoe48pZTg0EkTNndP2fEqO0118CwLho6wFVaDChMOARM90QXZFuVLjuOa5ZMxOPI/N3IDax359ykqTy/yG2s2BmwuKNo6a7vSJOpzu6C01dq3kAFLUDyiSJR1b1rEhbePMCELgc0c6wYhv+z6qqrqxs7KurE82+TwjUfaYo=
before_install:
- make patch-config
- rm -rf !(.|..|.git)
- git checkout .
script:
- make
- make test

  
